export default function Body() {
  return (
    <>
      <p>
        Dive into the immersive world of <em>Blue Noise</em>, an audiovisual
        installation funded by Ocean Week Canada. Created by the BluHeron
        Collective, consisting of artists Christopher McLeod and Alex MacLean,
        this interactive experience explores the devastating impact of ocean
        noise pollution on marine life.
      </p>
      <p>
        Through projected visuals accompanied by a generative soundscape,
        participants witness the harmony of healthy marine ecosystems
        juxtaposed with the disruptive noise generated by human activities. As
        viewers maneuver their hands in front of a sensor, their actions
        trigger and modify the simulated pollution, offering a visceral
        connection to the consequences of our actions.
      </p>
      <h2>BluHeron Collective</h2>
      <p>
        BluHeron Collective, consisting of artists Christopher McLeod and Alex
        MacLean, is an open collective exploring sonic art through new
        technologies and modes of engagement. Their explorations intertwine
        realms of augmented and virtual reality infused with physicality
        through sonic landscapes. BluHeron invites audiences into
        transformative journeys through sound and immersive mediums. Weaving
        innovative technology and live performance, the collective creates
        alternative reflections on contemporary social and environmental
        topics in an attempt to spark meaningful dialogues and provoke
        contemplation.
      </p>
    </>
  )
}
